In [3]:
import sys
import os
sys.path.append(os.path.abspath("../"))

In [4]:
from quantum_attention import QuantumAttention
import numpy as np

qa = QuantumAttention(n_qubits=4, n_layers=1)

queries = [np.random.random(4) for _ in range(3)]
keys    = [np.random.random(4) for _ in range(3)]

print("Fidelity attention:")
print(qa.compute_attention(queries, keys, method="fidelity"))

print("\nSWAP-test attention:")
print(qa.compute_attention(queries, keys, method="swap"))


Fidelity attention:
[[0.34517689 0.36514931 0.2896738 ]
 [0.33362846 0.374034   0.29233754]
 [0.33808059 0.34720405 0.31471536]]

SWAP-test attention:
[[0.3539706  0.35967968 0.28634972]
 [0.33747412 0.3714777  0.29104818]
 [0.34434142 0.34780211 0.30785647]]


# Quantum Attention Block — Summary

**Objective:**  
Implement a standalone quantum attention block to explore quantum alternatives to classical attention mechanisms, integrating **Fidelity Kernel** and **SWAP-Test**.

**Implementation Highlights:**  
- Quantum Attention Block built using **PennyLane** with a small **Variational Quantum Circuit (VQC)**.  
- **Two similarity methods implemented:**
  1. **Fidelity Kernel:** Exact state overlap between query and key quantum states; fast but simulator-only.  
  2. **SWAP-Test:** Shot-based quantum circuit estimation of state overlap; captures true quantum measurement behavior.  
- Workflow: Classical query & key vectors → quantum encoding → VQC → similarity computation → softmax → attention weights.  
- Standalone Testing: Can be tested independently, without a full transformer, using random query/key vectors.  
- Observations: 
  - Fidelity and SWAP-Test produce similar attention distributions.  
  - SWAP-Test introduces slight noise due to shot-based estimation.  
  - Attention matrices behave as expected: higher similarity → higher attention weight.

**Key Takeaways / Next Directions:**  
- Quantum attention is feasible as a standalone module.  
- Fidelity Kernel is efficient for simulation; SWAP-Test is realistic for real quantum hardware.  
- Can integrate into larger architectures (e.g., quantum transformer) in future experiments.  
- Further steps: trainable parameters, value aggregation, scaling to more qubits, comparative studies with classical attention.

**Conclusion:**  
The standalone quantum attention block demonstrates that **Fidelity and SWAP-Test concepts are meaningful and practical** in a quantum ML context, and testing can be done without the full transformer architecture.